# Generated by Django 3.2.7 on 2022-06-25 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationcompleted',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='audio_0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_0', to='assets.audio'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='audio_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_1', to='assets.audio'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='audio_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_2', to='assets.audio'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='audio_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_3', to='assets.audio'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='audio_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_4', to='assets.audio'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='audio_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_5', to='assets.audio'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='audio_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_6', to='assets.audio'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='audio_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_7', to='assets.audio'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='audio_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_8', to='assets.audio'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='audio_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_9', to='assets.audio'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='unit',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='courses.unit'),
        ),
    ]
