# Generated by Django 3.2.7 on 2022-04-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
