# Generated by Django 3.2.7 on 2022-05-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_alter_conversation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
