# Generated by Django 3.2.7 on 2021-12-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='is_correct_choice',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_correct_choice',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_correct_choice',
        ),
    ]
