# Generated by Django 3.2.7 on 2022-02-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollySpeaker',
            new_name='Voice',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='pollyText',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='speaker',
            new_name='voice',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='is_polly',
        ),
        migrations.AddField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('AWS', 'AWS'), ('GCS', 'GCS'), ('SELF_RECORDED', 'SELF_RECORDED')], default='SELF_RECORDED', max_length=250),
        ),
    ]
