# Generated by Django 3.2.7 on 2022-02-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20220205_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='service',
            field=models.CharField(blank=True, choices=[('AWS', 'AWS'), ('GCS', 'GCS'), ('SELF_RECORDED', 'SELF_RECORDED')], default='SELF_RECORDED', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='type',
            field=models.CharField(blank=True, choices=[('AWS', 'AWS'), ('GCS', 'GCS'), ('SELF_RECORDED', 'SELF_RECORDED')], default='SELF_RECORDED', max_length=250, null=True),
        ),
    ]
