# Generated by Django 3.2.7 on 2021-12-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20211211_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='pollyText',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
