# Generated by Django 3.2.7 on 2022-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20220205_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['text']},
        ),
        migrations.AddField(
            model_name='voice',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='Photos'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='is_re_record',
            field=models.BooleanField(default=True),
        ),
    ]
