# Generated by Django 3.2.7 on 2021-12-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20211212_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollyspeaker',
            name='nickName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.pollyspeaker'),
        ),
    ]
