# Generated by Django 3.2.7 on 2022-04-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20220411_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='title',
        ),
        migrations.AlterField(
            model_name='audio',
            name='type',
            field=models.CharField(blank=True, choices=[('CLOUD', 'CLOUD'), ('SELF_RECORD', 'SELF_RECORD')], default='CLOUD', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='service',
            field=models.CharField(blank=True, choices=[('AWS', 'AWS'), ('GCS', 'GCS')], max_length=250, null=True),
        ),
    ]
