# Generated by Django 3.2.7 on 2021-12-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20211212_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='is_re_record',
            field=models.BooleanField(default=False),
        ),
    ]
