# Generated by Django 3.2.7 on 2022-05-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20220412_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
