# Generated by Django 3.2.7 on 2022-01-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_audio_is_re_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title']},
        ),
    ]
