# Generated by Django 3.2.7 on 2021-09-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_unit_section'),
        ('unitTests', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unittest',
            options={},
        ),
        migrations.AlterField(
            model_name='unittest',
            name='unit',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitTests', to='units.unit'),
        ),
    ]
