# Generated by Django 3.2.7 on 2021-09-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitTests', '0003_auto_20210927_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='unitTests.unittest'),
        ),
    ]
