# Generated by Django 3.2.7 on 2022-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='course_photos')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(choices=[('GENERAL_ENGLISH', 'GENERAL_ENGLISH'), ('NURSARY', 'NURSARY'), ('SCHOOL_ENGLISH_KERALA', 'SCHOOL_ENGLISH_KERALA'), ('GENERAL_ARABIC', 'GENERAL_ARABIC')], default='GENERAL_ENGLISH', max_length=250)),
                ('language', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('ARABIC', 'ARABIC'), ('MALAYALAM', 'MALAYALAM'), ('SPANISH', 'SPANISH'), ('FRENCH', 'FRENCH'), ('GERMAN', 'GERMAN')], default='ENGLISH', max_length=250)),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'courses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enrolled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Enrollled Courses',
                'ordering': ['student', 'course'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='section_photos')),
                ('has_units', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('vocab_count', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='unit_photos')),
            ],
            options={
                'verbose_name_plural': 'units',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UnitCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Completedunits',
                'ordering': ['student', 'unit'],
            },
        ),
    ]
