# Generated by Django 3.2.7 on 2022-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='course_photos')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='course_certificats')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('course_fee', models.CharField(blank=True, default='1000', max_length=10, null=True)),
                ('discount', models.CharField(blank=True, default='0.2', max_length=10, null=True)),
                ('is_free', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'courses',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('GENERAL_ENGLISH', 'GENERAL_ENGLISH'), ('NURSARY', 'NURSARY'), ('SCHOOL_ENGLISH_KERALA', 'SCHOOL_ENGLISH_KERALA'), ('GENERAL_ARABIC', 'GENERAL_ARABIC')], max_length=250, null=True)),
                ('language', models.CharField(blank=True, choices=[('ENGLISH', 'ENGLISH'), ('ARABIC', 'ARABIC'), ('MALAYALAM', 'MALAYALAM'), ('SPANISH', 'SPANISH'), ('FRENCH', 'FRENCH'), ('GERMAN', 'GERMAN')], default='ENGLISH', max_length=250, null=True)),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_unit', models.IntegerField(blank=True, default=1, null=True)),
                ('is_enrolled', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Enrollled Courses',
                'ordering': ['student', 'course'],
            },
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('class_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'LiveClasses',
                'ordering': ['class_date'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=1, null=True)),
                ('order', models.FloatField(blank=True, default=1, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('vocab_count', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='unit_photos')),
            ],
            options={
                'verbose_name_plural': 'units',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UnitCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Completedunits',
                'ordering': ['student', 'unit'],
            },
        ),
    ]
