# Generated by Django 3.2.7 on 2021-10-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_section_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='section',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Units', to='courses.section'),
        ),
    ]
