# Generated by Django 3.2.7 on 2022-02-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='course_certificats'),
        ),
    ]
