# Generated by Django 3.2.7 on 2021-10-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211009_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_for_nursary',
            new_name='is_for_nursery',
        ),
    ]
