# Generated by Django 3.2.7 on 2022-05-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='order',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
