# Generated by Django 3.2.7 on 2021-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_unit_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
