# Generated by Django 3.2.7 on 2021-10-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_is_for_nursary_course_is_for_nursery'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='course_photos'),
        ),
    ]
