# Generated by Django 3.2.7 on 2021-11-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211028_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='has_units',
            field=models.BooleanField(default=True),
        ),
    ]
