# Generated by Django 3.2.7 on 2021-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_section_has_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('GNERAL_ENGLISH', 'General_English'), ('SCHOOL_ENGLISH_KERALA', 'School_English_Kerala'), ('GENERAL_ARABIC', 'General_Arabic')], default='General_English', max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('ARABIC', 'Arabic'), ('MALAYALAM', 'Malayalam'), ('SPANISH', 'Spanish'), ('FRENCH', 'French'), ('GERMAN', 'German')], default='English', max_length=250),
        ),
    ]
