# Generated by Django 3.2.7 on 2022-05-17 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_liveclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.unit'),
        ),
    ]
