# Generated by Django 3.2.7 on 2022-01-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220101_0553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order'], 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order'], 'verbose_name_plural': 'units'},
        ),
        migrations.AddField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('GENERAL_ENGLISH', 'GENERAL_ENGLISH'), ('NURSARY', 'NURSARY'), ('SCHOOL_ENGLISH_KERALA', 'SCHOOL_ENGLISH_KERALA'), ('GENERAL_ARABIC', 'GENERAL_ARABIC')], default='GENERAL_ENGLISH', max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('ARABIC', 'ARABIC'), ('MALAYALAM', 'MALAYALAM'), ('SPANISH', 'SPANISH'), ('FRENCH', 'FRENCH'), ('GERMAN', 'GERMAN')], default='ENGLISH', max_length=250),
        ),
    ]
