# Generated by Django 3.2.7 on 2022-05-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_liveclass_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-order'], 'verbose_name_plural': 'courses'},
        ),
    ]
