# Generated by Django 3.2.7 on 2022-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.CharField(blank=True, default='1000', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.CharField(blank=True, default='20%', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
