# Generated by Django 3.2.7 on 2022-01-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220110_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='unit_photos'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Units', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='section',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UnitsSections', to='courses.section'),
        ),
    ]
