# Generated by Django 3.2.7 on 2022-05-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220525_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.CharField(blank=True, default='0.2', max_length=10, null=True),
        ),
    ]
