# Generated by Django 3.2.7 on 2022-05-27 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseCategories', to='courses.coursecategory'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='language',
            field=models.CharField(blank=True, choices=[('ENGLISH', 'ENGLISH'), ('ARABIC', 'ARABIC'), ('MALAYALAM', 'MALAYALAM'), ('SPANISH', 'SPANISH'), ('FRENCH', 'FRENCH'), ('GERMAN', 'GERMAN')], default='ENGLISH', max_length=250, null=True),
        ),
    ]
