# Generated by Django 3.2.7 on 2022-01-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_enrolledcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='is_completed',
            new_name='is_enrolled',
        ),
    ]
