# Generated by Django 3.2.7 on 2022-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_rename_is_completed_enrolledcourse_is_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
