# Generated by Django 3.2.7 on 2022-01-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_unit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
