# Generated by Django 3.2.7 on 2022-01-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_unit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='vocab_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
