# Generated by Django 3.2.7 on 2022-05-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_enrolledcourse_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
