# Generated by Django 3.2.7 on 2022-05-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_liveclass_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
