# Generated by Django 3.2.7 on 2021-10-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_section_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='section_photos'),
        ),
    ]
