# Generated by Django 3.2.7 on 2021-10-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct_choice', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quiz_photo_choices')),
            ],
        ),
        migrations.CreateModel(
            name='TextChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct_choice', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('is_indipendent', models.BooleanField(default=False)),
                ('is_course_based', models.BooleanField(default=False)),
                ('is_section_based', models.BooleanField(default=False)),
                ('is_unit_based', models.BooleanField(default=False)),
                ('is_lesson_based', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseQuizzes', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessonQuizzes', to='lessons.lesson')),
                ('section', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitQuizzes', to='courses.section')),
                ('unit', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitQuizzes', to='courses.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('has_photo_choices', models.BooleanField(default=False)),
                ('has_text_choices', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='quiz_videos')),
                ('has_audio', models.BooleanField(default=False)),
                ('audio', models.FileField(blank=True, null=True, upload_to='quiz_audios')),
                ('has_text', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
                ('has_photo', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quiz_photos')),
                ('photo_choices', models.ManyToManyField(to='quizzes.PhotoChoices')),
                ('quiz', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionQuizzes', to='quizzes.quiz')),
                ('text_choices', models.ManyToManyField(to='quizzes.TextChoices')),
            ],
        ),
    ]
