# Generated by Django 3.2.7 on 2021-12-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('assets', '0002_auto_20211211_1327'),
        ('courses', '0005_section_has_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('is_correct_choice', models.BooleanField(default=False)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.audio')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('is_correct_choice', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.photo')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHOICE', 'Choice'), ('DRAG', 'DRAG')], default='Choice', max_length=250)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('LESSONBASED', 'Lesson_Based'), ('UNITBASED', 'Unit_Based'), ('SECTIONBASED', 'Section_Based'), ('COURSEBASED', 'Course_Based'), ('INDIPENDENT', 'Independent')], default='Lesson_Based', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TextChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('is_correct_choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('course', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseQuizzes', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessonQuizzes', to='lessons.lesson')),
                ('section', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitQuizzes', to='courses.section')),
                ('type', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizzes.quiztype')),
                ('unit', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitQuizzes', to='courses.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.CharField(blank=True, max_length=250, null=True)),
                ('audio_choices', models.ManyToManyField(blank=True, null=True, to='quizzes.AudioChoices')),
                ('photo_choices', models.ManyToManyField(blank=True, null=True, to='quizzes.PhotoChoices')),
                ('questionType', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.questiontype')),
                ('quiz', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizzes.quiz')),
                ('text_choices', models.ManyToManyField(blank=True, null=True, to='quizzes.TextChoices')),
            ],
        ),
    ]
