# Generated by Django 3.2.7 on 2022-01-30 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_initial'),
        ('assets', '0001_initial'),
        ('courses', '0002_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcompleted',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseQuizzes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessonQuizzes', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='unit',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitQuizzes', to='courses.unit'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.audio'),
        ),
        migrations.AddField(
            model_name='question',
            name='photo_option_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_1', to='assets.photo'),
        ),
        migrations.AddField(
            model_name='question',
            name='photo_option_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_2', to='assets.photo'),
        ),
        migrations.AddField(
            model_name='question',
            name='photo_option_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_3', to='assets.photo'),
        ),
        migrations.AddField(
            model_name='question',
            name='photo_option_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_4', to='assets.photo'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='photochoices',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.photo'),
        ),
        migrations.AddField(
            model_name='audiochoices',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.audio'),
        ),
    ]
