# Generated by Django 3.2.7 on 2021-10-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo_choices',
            field=models.ManyToManyField(blank=True, to='quizzes.PhotoChoices'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_choices',
            field=models.ManyToManyField(blank=True, to='quizzes.TextChoices'),
        ),
    ]
