# Generated by Django 3.2.7 on 2022-03-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='posType',
            field=models.CharField(blank=True, choices=[('NotPos', 'NotPos'), ('Noun', 'Noun'), ('Singular', 'Singular'), ('Place', 'Place'), ('ProperNoun', 'ProperNoun'), ('Plural', 'Plural'), ('Uncountable', 'Uncountable'), ('Possessive', 'Possessive'), ('Verb', 'Verb'), ('PresentTense', 'PresentTense'), ('Infinitive', 'Infinitive'), ('Gerund', 'Gerund'), ('PastTense', 'PastTense'), ('PerfectTense', 'PerfectTense'), ('FuturePerfect', 'FuturePerfect'), ('Participle', 'Participle'), ('PhrasalVerb', 'PhrasalVerb'), ('Adjective', 'Adjective'), ('Negative', 'Negative'), ('Superlative', 'Superlative'), ('Comparative', 'Comparative'), ('Adverb', 'Adverb'), ('Preposition', 'Preposition'), ('QuestionWord', 'QuestionWord'), ('Pronoun', 'Pronoun')], default='NotPos', max_length=250, null=True),
        ),
    ]
