# Generated by Django 3.2.7 on 2021-12-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20211211_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('LESSONBASED', 'Lesson_Based'), ('UNITBASED', 'Unit_Based'), ('SECTIONBASED', 'Section_Based'), ('COURSEBASED', 'Course_Based'), ('INDIPENDENT', 'Independent')], default='Lesson_Based', max_length=250),
        ),
        migrations.DeleteModel(
            name='QuizType',
        ),
    ]
