# Generated by Django 3.2.7 on 2021-12-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20211211_1327'),
        ('quizzes', '0003_auto_20211211_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.audio'),
        ),
    ]
