# Generated by Django 3.2.7 on 2021-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20211210_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
