# Generated by Django 3.2.7 on 2021-12-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='assetType',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('TEXT', 'Text'), ('Audio', 'Audio'), ('Video', 'Video')], default='Photo', max_length=250),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
    ]
