# Generated by Django 3.2.7 on 2022-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('1', 'OPTION_1'), ('2', 'OPTION_2'), ('3', 'OPTION_3'), ('4', 'OPTION_4'), ('ANY', 'ANY')], max_length=250, null=True),
        ),
    ]
