# Generated by Django 3.2.7 on 2022-04-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_question_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='Photos'),
        ),
    ]
