# Generated by Django 3.2.7 on 2021-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_questiontype_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'Choice'), ('DRAG', 'Drag'), ('MATCH', 'Match')], default='Choice', max_length=250),
        ),
    ]
