# Generated by Django 3.2.7 on 2022-04-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20220412_0806'),
        ('quizzes', '0007_quiz_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.audio'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('PHOTO_OPTIONS', 'PHOTO_OPTIONS'), ('TEXT_OPTIONS', 'TEXT_OPTIONS'), ('DRAG', 'DRAG'), ('SPEAK', 'SPEAK'), ('WRITE', 'WRITE'), ('MATCH', 'MATCH'), ('FILL_IN_BLANK', 'FILL_IN_BLANK'), ('FILL_IN_BLANK_WITH_PHOTO', 'FILL_IN_BLANK_WITH_PHOTO'), ('FILL_IN_BLANK_WITH_PHOTO_CON', 'FILL_IN_BLANK_WITH_PHOTO_CON'), ('READING', 'READING')], default='FILL_IN_BLANK_WITH_PHOTO', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('1', 'OPTION_1'), ('2', 'OPTION_2'), ('3', 'OPTION_3'), ('4', 'OPTION_4'), ('ANY', 'ANY')], default='ANY', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'Choice'), ('DRAG', 'Drag'), ('MATCH', 'Match'), ('FILL_IN_BLANK', 'Fill_In_Blank'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing'), ('READING', 'READING')], default='Choice', max_length=250),
        ),
    ]
