# Generated by Django 3.2.7 on 2022-01-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_questiontype_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='questiontype',
            options={'ordering': ['type', 'assetType', 'has_audio', 'pos']},
        ),
    ]
