# Generated by Django 3.2.7 on 2022-04-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20220415_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcompleted',
            name='score',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('PHOTO_OPTIONS', 'PHOTO_OPTIONS'), ('TEXT_OPTIONS', 'TEXT_OPTIONS'), ('DRAG', 'DRAG'), ('SPEAK', 'SPEAK'), ('WRITE', 'WRITE'), ('MATCH', 'MATCH'), ('DIALOGUE', 'DIALOGUE'), ('FILL_IN_BLANK', 'FILL_IN_BLANK'), ('FILL_IN_BLANK_WITH_PHOTO', 'FILL_IN_BLANK_WITH_PHOTO'), ('FILL_IN_BLANK_WITH_PHOTO_CON', 'FILL_IN_BLANK_WITH_PHOTO_CON'), ('READING_COMPREHENSION', 'READING_COMPREHENSION'), ('LISTENING_COMPREHENSION', 'LISTENING_COMPREHENSION')], default='FILL_IN_BLANK_WITH_PHOTO', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'Choice'), ('DRAG', 'Drag'), ('MATCH', 'Match'), ('FILL_IN_BLANK', 'Fill_In_Blank'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing'), ('READING_COMPREHENSION', 'READING_COMPREHENSION'), ('LISTENING_COMPREHENSION', 'LISTENING_COMPREHENSION')], default='Choice', max_length=250),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(blank=True, choices=[('LISTENING', 'LISTENING'), ('SPEAKING', 'SPEAKING'), ('WRITING', 'WRITING'), ('READING', 'READING'), ('GRAMMAR', 'GRAMMAR'), ('VOCABULARY', 'VOCABULARY'), ('DIALOGUE', 'DIALOGUE'), ('UNIT_TEST', 'UNIT_TEST'), ('GENERAL_ENGLISH', 'GENERAL_ENGLISH'), ('GENERAL_ARABIC', 'GENERAL_ARABIC'), ('OTHER', 'OTHER')], default='OTHER', max_length=250, null=True),
        ),
    ]
