# Generated by Django 3.2.7 on 2022-01-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20220110_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(blank=True, choices=[('LISTENING', 'LISTENING'), ('SPEAKING', 'SPEAKING'), ('WRITING', 'WRITING'), ('READING', 'READING'), ('GRAMMER', 'GRAMMER'), ('OTHER', 'OTHER')], default='OTHER', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(blank=True, choices=[('LESSONBASED', 'Lesson_Based'), ('UNITBASED', 'Unit_Based'), ('SECTIONBASED', 'Section_Based'), ('COURSEBASED', 'Course_Based'), ('INDIPENDENT', 'Independent')], default='Lesson_Based', max_length=250, null=True),
        ),
    ]
