# Generated by Django 3.2.7 on 2022-01-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20220110_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='assetType',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('TEXT', 'Text'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='Other', max_length=250),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'Choice'), ('DRAG', 'Drag'), ('MATCH', 'Match'), ('FILL_IN_BLANK', 'Fill_In_Blank'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing')], default='Choice', max_length=250),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(blank=True, choices=[('LISTENING', 'LISTENING'), ('SPEAKING', 'SPEAKING'), ('WRITING', 'WRITING'), ('READING', 'READING'), ('GRAMMAR', 'GRAMMAR'), ('VOCABULARY', 'VOCABULARY'), ('UNIT_TEST', 'UNIT_TEST'), ('OTHER', 'OTHER')], default='OTHER', max_length=250, null=True),
        ),
    ]
