# Generated by Django 3.2.7 on 2022-01-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_auto_20220114_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_1',
            new_name='text_option_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_2',
            new_name='text_option_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_3',
            new_name='text_option_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_4',
            new_name='text_option_4',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('OPTION_1', '1'), ('OPTION_2', '2'), ('OPTION_3', '3'), ('OPTION_4', '4')], max_length=250, null=True),
        ),
    ]
