# Generated by Django 3.2.7 on 2022-01-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_auto_20220114_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('1', 'OPTION_1'), ('OPTION_2', '2'), ('OPTION_3', '3'), ('OPTION_4', '4')], max_length=250, null=True),
        ),
    ]
