# Generated by Django 3.2.7 on 2022-01-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_question_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('1', 'OPTION_1'), ('2', 'OPTION_2'), ('3', 'OPTION_3'), ('4', 'OPTION_4')], max_length=250, null=True),
        ),
    ]
