# Generated by Django 3.2.7 on 2022-04-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_alter_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_practice',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
