# Generated by Django 3.2.7 on 2022-01-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20220110_1334'),
        ('quizzes', '0013_alter_question_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo_option_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_1', to='assets.photo'),
        ),
        migrations.AddField(
            model_name='question',
            name='photo_option_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_2', to='assets.photo'),
        ),
        migrations.AddField(
            model_name='question',
            name='photo_option_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_3', to='assets.photo'),
        ),
        migrations.AddField(
            model_name='question',
            name='photo_option_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='photo_4', to='assets.photo'),
        ),
    ]
