# Generated by Django 3.2.7 on 2022-05-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_quiz_is_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_practice',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
