# Generated by Django 3.2.7 on 2022-05-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_auto_20220501_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
