# Generated by Django 3.2.7 on 2022-01-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_remove_question_questiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='section',
        ),
    ]
