# Generated by Django 3.2.7 on 2022-05-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_auto_20220509_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
