# Generated by Django 3.2.7 on 2022-01-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_remove_quiz_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='type',
        ),
    ]
