# Generated by Django 3.2.7 on 2022-01-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_quiz_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['order', 'unit', 'category', 'title']},
        ),
    ]
