# Generated by Django 3.2.7 on 2021-09-30 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0002_alter_unit_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('has_video', models.BooleanField(default=False)),
                ('has_audi', models.BooleanField(default=False)),
                ('has_text', models.BooleanField(default=False)),
                ('has_photo', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lesson_photos')),
                ('video', models.FileField(blank=True, null=True, upload_to='lesson_video')),
                ('audio', models.FileField(blank=True, null=True, upload_to='lesson_audio')),
                ('unit', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='units.unit')),
            ],
            options={
                'verbose_name_plural': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.SmallIntegerField()),
                ('choices', models.ManyToManyField(to='lessons.LessonQuestionChoice')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessonsQuestions', to='lessons.lesson')),
            ],
        ),
    ]
