# Generated by Django 3.2.7 on 2021-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonitem',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonitem',
            name='type',
            field=models.CharField(choices=[('AUDIOBASED', 'Audio_based'), ('PHOTOBASED', 'Photo_Based'), ('VIDOEBASED', 'Video_Based')], default='Audio_based', max_length=250),
        ),
    ]
