# Generated by Django 3.2.7 on 2021-09-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='readingtText',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
