# Generated by Django 3.2.7 on 2021-10-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_unit_section'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lessons', to='courses.unit'),
        ),
        migrations.AlterField(
            model_name='lessonitem',
            name='lesson',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LessonItems', to='lessons.lesson'),
        ),
    ]
