# Generated by Django 3.2.7 on 2021-10-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20211013_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
