# Generated by Django 3.2.7 on 2022-03-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20220205_0648'),
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='section',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.video'),
        ),
    ]
