# Generated by Django 3.2.7 on 2021-11-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211028_1129'),
        ('lessons', '0003_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sections', to='courses.section'),
        ),
    ]
