# Generated by Django 3.2.7 on 2022-01-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lessonitem_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='lessonitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='lessonitem',
            name='type',
            field=models.CharField(choices=[('ONLY_VIDEO', 'Only_Video'), ('ONLY_PHOTO', 'Only_Photo'), ('PHOTO_AND_AUDIO', 'Photo_And_Audio')], default='PHOTO_AND_AUDIO', max_length=250),
        ),
    ]
