# Generated by Django 3.2.7 on 2022-01-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20220110_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['unit', 'order']},
        ),
    ]
