# Generated by Django 3.2.7 on 2021-10-01 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessoncompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncompleted',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessonCompleted', to='lessons.lesson'),
        ),
    ]
