# Generated by Django 3.2.7 on 2021-10-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_section_course'),
        ('lessons', '0006_alter_lessoncompleted_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionLessons', to='sections.section'),
        ),
    ]
