# Generated by Django 3.2.7 on 2022-05-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bug_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='is_resolved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
