# Generated by Django 3.2.7 on 2022-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20220530_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='bug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
